# -*- coding: utf-8 -*-
"""YouTube_Chatbot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xcWXlMkPQz0xngf_HHuxjOmBmOKCCgFw
"""

import os
#GOOGLE_API_KEY = os.environ['GOOGLE_API_KEY']
#hf_token = os.environ["HUGGINGFACEHUB_API_TOKEN"] 

"""**LIBRARIES**"""


from youtube_transcript_api import YouTubeTranscriptApi, TranscriptsDisabled
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_openai import OpenAIEmbeddings, ChatOpenAI
from langchain_google_genai import GoogleGenerativeAIEmbeddings, ChatGoogleGenerativeAI
from langchain_huggingface import HuggingFaceEmbeddings
from langchain_community.vectorstores import FAISS
from langchain_core.prompts import PromptTemplate
from langchain_core.output_parsers import StrOutputParser
from dotenv import load_dotenv


# ============================================================
# LOAD ENVIRONMENT VARIABLES
# ============================================================

load_dotenv()

# ============================================================
# 1.a  Indexing (Document-ingestion)
# # ==========================================================

#video_id = "LGGN_HLJ2g0"
video_id = "Gfr50f6ZBvo"
try:
  api = YouTubeTranscriptApi()
  transcript_list = api.fetch(video_id, languages =["en"])
  youtube_transcript = ' '.join(chunk.text for chunk in transcript_list)
except TranscriptsDisabled:
  raise ValueError("Transcript is not available for this video.")

# ============================================================
# 1.b - Indexing (Text_Spliter)
# # ==========================================================

splitter = RecursiveCharacterTextSplitter(chunk_size = 1000, chunk_overlap = 200)
chunks = splitter.create_documents([youtube_transcript])

#print(len(chunks))

#chunks[167]


# =======================================================================
# 1.C & 1.D - Indexing (Embedding Generation and Storing in Vector Store)
# # =====================================================================

embedding = HuggingFaceEmbeddings(model_name = "sentence-transformers/all-MiniLM-L6-v2")
vector_store = FAISS.from_documents(chunks, embedding)

#len(vectore_store.index_to_docstore_id)

#vectore_store.index_to_docstore_id

#vectore_store.get_by_ids(['d171ff04-ab9a-4273-8ddf-553e2b2a7c93'])


# ====================================================
# 2 - Retrieval
# # ==================================================

retriever = vector_store.as_retriever(search_type = 'similarity', search_kwargs = {'k':4})

#retriever

#retriever.invoke("what is deepmind")

# ====================================================
# 3 - Augmentation
# # ==================================================

prompt = PromptTemplate(
    template = """
You are a helpful assistant.
      Answer ONLY from the provided transcript context.
      If the context is insufficient, just say you don't know.

      {context}
      Question: {question}
""",
    input_variables = ["context", "question"])

question = "is the topic of nuclear fusion discussed in this video? if yes then what was discussed"

reterieved_docs = retriever.invoke(question)

#reteriever_docs

context_text = "\n\n".join([doc.page_content for doc in reterieved_docs])

#context_text

final_prompt = prompt.invoke({"context": context_text, "question": question})

#final_prompt

# ====================================================
# 3 - Generation
# # ==================================================
llm = ChatGoogleGenerativeAI(model = "gemini-2.5-flash", temperature = 0.2)
answer = llm.invoke(final_prompt)
#answer.content
# ====================================================
# 4 - Building a Chain
# # ==================================================

from langchain_core.runnables import RunnableParallel, RunnablePassthrough, RunnableLambda

def format_docs(reteriever_docs):
  context_text = "\n\n".join(doc.page_content for doc in reteriever_docs)
  return context_text

parallel_chain = RunnableParallel(
    {
        "context": retriever | RunnableLambda(format_docs),
        "question": RunnablePassthrough()
    }
)

#parallel_chain.invoke("who is deemis")

parser = StrOutputParser()

chain = parallel_chain | prompt | llm | parser
question = "what is the role of saad in this video"
answer = chain.invoke(question)

print("\n================ ANSWER ================\n")

print(answer)
