"""add_user_dept_and_chat_dept

Revision ID: 456c441d8402
Revises: 5420559ac407
Create Date: 2026-09-11 19:20:12.999146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '456c441d8402'
down_revision: Union[str, Sequence[str], None] = '5420559ac407'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_history', sa.Column('department_id', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_chat_history_company_id'), table_name='chat_history')
    op.drop_index(op.f('ix_chat_history_user_id'), table_name='chat_history')
    op.create_index('ix_chat_history_user_created', 'chat_history', ['user_id', 'created_at'], unique=False)
    op.create_foreign_key(op.f('fk_chat_history_department_id_departments'), 'chat_history', 'departments', ['department_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_query_logs_company_id'), table_name='query_logs')
    op.drop_index(op.f('ix_query_logs_department_id'), table_name='query_logs')
    op.drop_index(op.f('ix_query_logs_user_id'), table_name='query_logs')
    op.create_index('ix_query_logs_company_created', 'query_logs', ['company_id', 'created_at'], unique=False)
    op.create_index('ix_query_logs_company_department', 'query_logs', ['company_id', 'department_id', 'created_at'], unique=False)
    op.add_column('users', sa.Column('department_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.alter_column('users', 'company_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=320),
               existing_nullable=False)
    op.create_index('ix_users_company_department', 'users', ['company_id', 'department_id'], unique=False)
    op.create_index('ix_users_company_role', 'users', ['company_id', 'role'], unique=False)
    op.create_index(op.f('ix_users_department_id'), 'users', ['department_id'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_foreign_key(op.f('fk_users_department_id_departments'), 'users', 'departments', ['department_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_users_department_id_departments'), 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_department_id'), table_name='users')
    op.drop_index('ix_users_company_role', table_name='users')
    op.drop_index('ix_users_company_department', table_name='users')
    op.alter_column('users', 'email',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('users', 'company_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'department_id')
    op.drop_index('ix_query_logs_company_department', table_name='query_logs')
    op.drop_index('ix_query_logs_company_created', table_name='query_logs')
    op.create_index(op.f('ix_query_logs_user_id'), 'query_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_query_logs_department_id'), 'query_logs', ['department_id'], unique=False)
    op.create_index(op.f('ix_query_logs_company_id'), 'query_logs', ['company_id'], unique=False)
    op.drop_constraint(op.f('fk_chat_history_department_id_departments'), 'chat_history', type_='foreignkey')
    op.drop_index('ix_chat_history_user_created', table_name='chat_history')
    op.create_index(op.f('ix_chat_history_user_id'), 'chat_history', ['user_id'], unique=False)
    op.create_index(op.f('ix_chat_history_company_id'), 'chat_history', ['company_id'], unique=False)
    op.drop_column('chat_history', 'department_id')
    # ### end Alembic commands ###
